create table if not exists public.t_region (
  region_id integer generated by default as identity primary key,
  region_name text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists t_region_region_name_idx on public.t_region (region_name);

alter table public.t_region enable row level security;

drop trigger if exists set_t_region_updated_at on public.t_region;

create trigger set_t_region_updated_at
before update on public.t_region
for each row
execute function public.set_updated_at();
