create table if not exists public.t_admin_audit_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  action text not null,
  branch_id integer,
  destination_branch_id integer,
  actor_email text,
  detail jsonb not null default '{}'::jsonb,
  before_data jsonb,
  after_data jsonb,
  created_at timestamp with time zone not null default now(),

  constraint t_admin_audit_log_entity_type_value check (
    entity_type in ('student', 'rombel', 'branch_school', 'academic_year', 'master_data', 'user')
  ),
  constraint t_admin_audit_log_action_value check (
    action in ('create', 'update', 'delete', 'mutate')
  ),
  constraint t_admin_audit_log_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_admin_audit_log_destination_branch_id_fkey foreign key (destination_branch_id)
    references public.t_branch (branch_id)
);

create index if not exists t_admin_audit_log_created_at_idx
on public.t_admin_audit_log (created_at desc);

create index if not exists t_admin_audit_log_entity_idx
on public.t_admin_audit_log (entity_type, entity_id);

alter table public.t_admin_audit_log enable row level security;
