create table if not exists public.t_admin_audit_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text,
  action text not null,
  branch_id integer,
  destination_branch_id integer,
  actor_email text,
  detail jsonb not null default '{}'::jsonb,
  before_data jsonb,
  after_data jsonb,
  created_at timestamp with time zone not null default now(),

  constraint t_admin_audit_log_entity_type_value check (
    entity_type in ('student', 'rombel', 'branch_school', 'academic_year', 'master_data', 'user')
  ),
  constraint t_admin_audit_log_action_value check (
    action in ('create', 'update', 'delete', 'mutate')
  ),
  constraint t_admin_audit_log_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_admin_audit_log_destination_branch_id_fkey foreign key (destination_branch_id)
    references public.t_branch (branch_id)
);

create index if not exists t_admin_audit_log_created_at_idx
on public.t_admin_audit_log (created_at desc);

create index if not exists t_admin_audit_log_entity_idx
on public.t_admin_audit_log (entity_type, entity_id);

alter table public.t_admin_audit_log enable row level security;

drop policy if exists "admin can read admin audit logs" on public.t_admin_audit_log;
create policy "admin can read admin audit logs"
on public.t_admin_audit_log for select
to authenticated
using (public.is_admin());

create table if not exists public.t_google_sheet_sync_log (
  id bigint generated by default as identity primary key,
  nis varchar(12) not null,
  action text not null,
  status text not null,
  actor_email text,
  attempts integer not null default 1,
  error_message text,
  last_attempt_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint t_google_sheet_sync_log_action_value check (
    action in ('create', 'update', 'delete', 'mutate', 'retry')
  ),
  constraint t_google_sheet_sync_log_status_value check (
    status in ('success', 'failed', 'skipped')
  )
);

create index if not exists t_google_sheet_sync_log_status_created_at_idx
on public.t_google_sheet_sync_log (status, created_at desc);

create index if not exists t_google_sheet_sync_log_nis_idx
on public.t_google_sheet_sync_log (nis);

alter table public.t_google_sheet_sync_log enable row level security;

drop trigger if exists set_t_google_sheet_sync_log_updated_at on public.t_google_sheet_sync_log;
create trigger set_t_google_sheet_sync_log_updated_at
before update on public.t_google_sheet_sync_log
for each row
execute function public.set_updated_at();

drop policy if exists "admin can read sheet sync logs" on public.t_google_sheet_sync_log;
create policy "admin can read sheet sync logs"
on public.t_google_sheet_sync_log for select
to authenticated
using (public.is_admin());
