create table if not exists public.t_branch_school (
  id bigint generated by default as identity primary key,
  npsn text not null,
  branch_id integer not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint t_branch_school_npsn_length check (char_length(npsn) = 8),
  constraint t_branch_school_branch_id_digits check (branch_id between 100 and 999),
  constraint t_branch_school_npsn_branch_id_unique unique (npsn, branch_id)
);

create index if not exists t_branch_school_npsn_idx on public.t_branch_school (npsn);
create index if not exists t_branch_school_branch_id_idx on public.t_branch_school (branch_id);

alter table public.t_branch_school enable row level security;

drop trigger if exists set_t_branch_school_updated_at on public.t_branch_school;

create trigger set_t_branch_school_updated_at
before update on public.t_branch_school
for each row
execute function public.set_updated_at();
