create table if not exists public.t_agent (
  agent_id integer generated by default as identity (start with 70000) primary key,
  agent_name text not null,
  agent_email text,
  branch_id integer,
  app_user_id uuid,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint t_agent_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_agent_app_user_id_fkey foreign key (app_user_id)
    references public.t_app_user (id) on delete set null
);

create index if not exists t_agent_agent_name_idx on public.t_agent (agent_name);
create index if not exists t_agent_branch_id_idx on public.t_agent (branch_id);

alter table public.t_agent enable row level security;

drop trigger if exists set_t_agent_updated_at on public.t_agent;

create trigger set_t_agent_updated_at
before update on public.t_agent
for each row
execute function public.set_updated_at();


create unique index if not exists t_agent_app_user_id_unique
on public.t_agent (app_user_id)
where app_user_id is not null;

create or replace function public.deactivate_agent_for_deleted_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.t_agent
  set
    is_active = false,
    app_user_id = null,
    updated_at = now()
  where app_user_id = old.id;

  return old;
end;
$$;

drop trigger if exists deactivate_agent_on_app_user_delete on public.t_app_user;

create trigger deactivate_agent_on_app_user_delete
before delete on public.t_app_user
for each row
execute function public.deactivate_agent_for_deleted_user();
