create table if not exists public.t_position (
  position_id integer generated by default as identity primary key,
  position_name text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint t_position_position_name_unique unique (position_name),
  constraint t_position_position_name_not_blank check (btrim(position_name) <> '')
);

create index if not exists t_position_position_name_idx
on public.t_position (position_name);

alter table public.t_position enable row level security;

drop trigger if exists set_t_position_updated_at on public.t_position;

create trigger set_t_position_updated_at
before update on public.t_position
for each row
execute function public.set_updated_at();


insert into public.t_position (position_id, position_name)
values
  (1, 'Territory Manager'),
  (2, 'Regional Manager'),
  (3, 'Branch Manager'),
  (4, 'Commercial & Marketing Coordinator'),
  (5, 'Academic & Operation'),
  (6, 'Commercial & Marketing Associate'),
  (7, 'Sales Coach Online'),
  (8, 'Admin Cluster'),
  (9, 'Admin Officer'),
  (10, 'Student Advisor'),
  (11, 'Student Advisor Kids'),
  (12, 'Field Education Consultant'),
  (13, 'Admin RGP')
on conflict (position_id) do update
set
  position_name = excluded.position_name,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.t_position', 'position_id'),
  greatest((select coalesce(max(position_id), 1) from public.t_position), 1),
  true
);
