create table if not exists public.t_google_sheet_sync_log (
  id bigint generated by default as identity primary key,
  nis varchar(12) not null,
  action text not null,
  status text not null,
  actor_email text,
  attempts integer not null default 1,
  error_message text,
  last_attempt_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint t_google_sheet_sync_log_action_value check (
    action in ('create', 'update', 'delete', 'mutate', 'retry')
  ),
  constraint t_google_sheet_sync_log_status_value check (
    status in ('success', 'failed', 'skipped')
  )
);

create index if not exists t_google_sheet_sync_log_status_created_at_idx
on public.t_google_sheet_sync_log (status, created_at desc);

create index if not exists t_google_sheet_sync_log_nis_idx
on public.t_google_sheet_sync_log (nis);

alter table public.t_google_sheet_sync_log enable row level security;

drop trigger if exists set_t_google_sheet_sync_log_updated_at on public.t_google_sheet_sync_log;
create trigger set_t_google_sheet_sync_log_updated_at
before update on public.t_google_sheet_sync_log
for each row
execute function public.set_updated_at();
