create table if not exists public.t_region (
  region_id integer generated by default as identity primary key,
  region_name text not null,
  regional_manager text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create index if not exists t_region_region_name_idx on public.t_region (region_name);

alter table public.t_region enable row level security;

drop trigger if exists set_t_region_updated_at on public.t_region;

create trigger set_t_region_updated_at
before update on public.t_region
for each row
execute function public.set_updated_at();

insert into public.t_region (region_id, region_name, regional_manager)
values
  (1, 'Regional - Madiun Raya', 'Azhar Zaki Ramadani, SE'),
  (2, 'Regional - Malang Raya', 'Rustam Effendy'),
  (3, 'Regional - Mojokerto Raya', 'Jenih Kusuma Lestari'),
  (4, 'Regional - Tapal Kuda', 'Elrey All Habib')
on conflict (region_id) do update
set
  region_name = excluded.region_name,
  regional_manager = excluded.regional_manager,
  updated_at = now();
