create table if not exists public.t_rombel (
  rombel_id integer generated by default as identity primary key,
  academic_year text,
  branch_id integer,
  grade_id integer,
  rombel_name text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  constraint t_rombel_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id),
  constraint t_rombel_grade_id_fkey foreign key (grade_id)
    references public.t_grade (grade_id),
  constraint t_rombel_academic_year_fkey foreign key (academic_year)
    references public.t_academic_year (academic_year) not valid
);

create index if not exists t_rombel_academic_year_idx on public.t_rombel (academic_year);
create index if not exists t_rombel_branch_id_idx on public.t_rombel (branch_id);
create index if not exists t_rombel_grade_id_idx on public.t_rombel (grade_id);

alter table public.t_rombel enable row level security;

drop trigger if exists set_t_rombel_updated_at on public.t_rombel;

create trigger set_t_rombel_updated_at
before update on public.t_rombel
for each row
execute function public.set_updated_at();
