create table if not exists public.t_agent (
  agent_id integer generated by default as identity (start with 70000) primary key,
  agent_name text not null,
  branch_id integer not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint t_agent_branch_id_fkey foreign key (branch_id)
    references public.t_branch (branch_id)
);

create index if not exists t_agent_agent_name_idx on public.t_agent (agent_name);
create index if not exists t_agent_branch_id_idx on public.t_agent (branch_id);

alter table public.t_agent enable row level security;

drop trigger if exists set_t_agent_updated_at on public.t_agent;

create trigger set_t_agent_updated_at
before update on public.t_agent
for each row
execute function public.set_updated_at();
